apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_URI: "mongodb+srv://gokulg12th2004:6369918149@cluster0.bmbqd.mongodb.net/ai_health_monitor?retryWrites=true&w=majority"
  SECRET_KEY: "your_secret_key"
  REFRESH_SECRET_KEY: "your_refresh_secret_key"
