version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://gokulg12th2004:6369918149@cluster0.bmbqd.mongodb.net/ai_health_monitor?retryWrites=true&w=majority