
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017         # Service port
      targetPort: 27017   # Pod container port
  selector:
    app: mongodb
  type: ClusterIP
