apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-health-monitor-service
spec:
  selector:
    app: ai-k8s-health-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
